before:
  hooks:
    - go mod download

builds:
  - goos:
      - linux
      - windows
      - darwin
    main: ./cmd/ptransfer/main.go

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
